[env:unihiker_k10]
platform = unihiker
board = unihiker_k10
framework = arduino
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
monitor_speed = 115200

; ESP32-S3 partition table
board_build.partitions = partitions.csv

build_flags =
  -DCONFIG_ESP32_PHY_MAX_TX_POWER=20
  -DBOARD_HAS_PSRAM
  -fno-optimize-sibling-calls

; U8g2 OLED display library
lib_deps =
  olikraus/U8g2@^2.34
